MarkovLevels = [
  {
    "levelName" : "Bloop",
    "startingLevel" : true,
    "RR" : "PPRRRRS",
    "PP" : "PPR",
    "SS" : "RSSS",
    "RP" : "PPR",
    "PR" : "PPRRRRS",
    "PS" : "RSSS",
    "RS" : "RSSS",
    "SR" : "PPRRRRS",
    "SP" : "PPR",
    "Description" : "Level 1 for M2Studio"
  },
  {
    "levelName" : "Yowza",
    "startingLevel" : false,
    "RR" : "PPRRRRS",
    "PP" : "PPRS",
    "SS" : "RSSSP",
    "RP" : "PPRS",
    "PR" : "PPRRRRS",
    "PS" : "RSSSP",
    "RS" : "RSSSP",
    "SR" : "PPRRRRS",
    "SP" : "PPRS",
    "Description" : "Level 2 for M2Studio"
  },
  {
    "levelName" : "Tethys",
    "startingLevel" : false,
    "RR" : "P",
    "PP" : "S",
    "SS" : "R",
    "RP" : "PPPPRS",
    "PR" : "R",
    "PS" : "SSSSSSPR",
    "RS" : "S",
    "SR" : "RRRRPS",
    "SP" : "P",
    "Description" : "A good place to start"
  },
  {
    "levelName" : "Deimos",
    "startingLevel" : false,
    "RR" : "P",
    "PP" : "RRRRRP",
    "SS" : "SSSSR",
    "RP" : "RP",
    "PR" : "PPPPRS",
    "PS" : "SSSSSP",
    "RS" : "S",
    "SR" : "RRRPS",
    "SP" : "PPPRS",
    "Description" : "A little more challenging"
  },
  {
    "levelName" : "Phobos",
    "startingLevel" : false,
    "RR" : "SSSSSRRPP",
    "PP" : "PPPPPRS",
    "SS" : "PPPR",
    "RP" : "RRP",
    "PR" : "RRRS",
    "PS" : "RRRS",
    "RS" : "SRRR",
    "SR" : "RRRS",
    "SP" : "PPPPPRS",
    "Description" : "Like Deimos, more challenging"
  },
  {
    "levelName" : "Callisto",
    "startingLevel" : false,
    "RR" : "RPS",
    "PP" : "PPPPPR",
    "SS" : "SSSR",
    "RP" : "PPPPPPR",
    "PR" : "RRRRRPS",
    "PS" : "R",
    "RS" : "SSSSSSR",
    "SR" : "RRRRRPS",
    "SP" : "R",
    "Description" : "Maybe more difficult? Not sure!"
  }
  ];